rem Generated by (c) Ispirer SQLWays 9.0 Build 6197 64bit Licensed to bgtu - Nikita - Belarus - Ispirer MnMTK 2020 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20200629)
rem Timestamp: Fri May 29 12:39:37 2020


cd "C:\Program Files\Ispirer\MnMTK2020"
SQLWays.exe  /D=D:\Studying\Course_3\Second_2sem\Web-Database\Labs\Lab_6\FSD1.dsn /U=swatar /P=1233214 /SROW=1 /TARGET=Oracle /TD=LABS /TU=LABS /TP=134576290Gobling /IMPORD=Clean /IMPS=Windows /DIR=D:\Studying\Course_3\Second_2sem\Web-Database\Labs\Lab_6 /STDEL=; /INI=C:\Users\HOME\Documents\Ispirer\SQLWays 2020\sqlways_db.ini /PRJF=C:\Users\HOME\Documents\Ispirer\SQLWays 2020\sqlways.xml /NSTOP /GCMD=sqlways_all.bat /LOG=sqlways.log /RPT=reports
"D:\Studying\Course_3\Second_2sem\Web-Database\Labs\Lab_6\sqlways_all.bat"
rem End script
