@echo off
if "%2"=="echo" (
  @echo on
  set SQLWAYS_CMD_ECHO=1
) else (
  @echo off
  set SQLWAYS_CMD_ECHO=0
)
echo.
echo Importing database objects to Oracle
rem Generated by (c) Ispirer SQLWays 9.0 Build 6197 64bit Licensed to bgtu - Nikita - Belarus - Ispirer MnMTK 2020 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20200629)
rem Timestamp: Fri May 29 12:39:37 2020

rem --------------------------------------------------------------
rem How to use this command file:

rem To import all database objects and data run:
rem 	sqlways_all.bat all

rem To import tables without data run:
rem 	sqlways_all.bat table

rem To import data into all tables run:
rem 	sqlways_all.bat import

rem To create indexes for all tables run:
rem 	sqlways_all.bat idx

rem To import all database objects without data run:
rem 	sqlways_all.bat ddl

rem --------------------------------------------------------------
echo Import initialization
call "swf_object_id.bat"

rem --------------------------------------------------------------
echo Importing tables (1 table)

call  "tablemigr.bat" %1

rem --------------------------------------------------------------
echo Importing functions ordered by dependency (2 functions)

call "fn_diagramobjects.bat"

rem --------------------------------------------------------------

rem End script
