@echo off
if %SQLWAYS_CMD_ECHO%==1 (@echo on)
echo Importing function SWF_OBJECT_ID to Oracle
rem Generated by (c) Ispirer SQLWays 9.0 Build 6197 64bit Licensed to bgtu - Nikita - Belarus - Ispirer MnMTK 2020 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20200629)
rem Timestamp: Fri May 29 12:39:37 2020

rem --------------------------------------------------------------

\\\\swatar-pc\\BIN\sqlplus LABS/134576290Gobling@LABS @swf_object_id.sql

rem --------------------------------------------------------------


rem End script
