-- DDL script for table TableMigr for Oracle
-- Generated by (c) Ispirer SQLWays 9.0 Build 6197 64bit Licensed to bgtu - Nikita - Belarus - Ispirer MnMTK 2020 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20200629)
-- Timestamp: Fri May 29 12:39:37 2020
-- Create table statement

SET DEFINE OFF


CREATE TABLE TableMigr
(
   Col1 NUMBER(10,0),
   Col2 VARCHAR2(50) 
);

EXIT;

