@echo off
if %SQLWAYS_CMD_ECHO%==1 (@echo on)
echo.
echo Importing table TableMigr to Oracle
rem Generated by (c) Ispirer SQLWays 9.0 Build 6197 64bit Licensed to bgtu - Nikita - Belarus - Ispirer MnMTK 2020 Microsoft SQL Server to Oracle Database Migration Demo License (1 month, 20200629)
rem Timestamp: Fri May 29 12:39:37 2020

rem --------------------------------------------------------------
rem How to use this command file:

rem To create table, constraints, import data and create indexes run:
rem 	tablemigr.bat all

rem To create table and its constraints run:
rem 	tablemigr.bat table

rem To import data into the table run:
rem 	tablemigr.bat import

rem To create indexes for the table run:
rem 	tablemigr.bat idx

rem To execute all DDL statements for the table run:
rem 	tablemigr.bat ddl

rem --------------------------------------------------------------
rem Define a task to perform

if "%1"=="" goto create_table
if %1==all goto create_table
if %1==table goto create_table
if %1==import goto import_data
if %1==idx goto create_idx
if %1==ddl goto create_table
goto end

rem --------------------------------------------------------------
:create_table
echo Creating table and its constraints using the Oracle SQL*Plus utility

\\\\swatar-pc\\BIN\sqlplus LABS/134576290Gobling@LABS @tablemigr_ddl.sql

if "%1"=="" goto import_data
if %1==all goto import_data
if %1==ddl goto create_idx
goto end

rem --------------------------------------------------------------
:import_data
echo Importing data using the Oracle SQL*Loader utility

\\\\swatar-pc\\BIN\sqlldr userid=LABS/134576290Gobling@LABS control=tablemigr.ctl log=tablemigr.log rows=1000 readsize=125000 bindsize=125000



if "%1"=="" goto create_idx
if %1==all goto create_idx
goto end

rem --------------------------------------------------------------
:create_idx


rem --------------------------------------------------------------
:end


rem End script
